#!/usr/bin/env ruby

require 'optparse'
require 'pry'

$options = {}
option_parse = OptionParser.new do |opt|
  opt.on('-f', '--force') do
    $options[:force] = true
    puts 'force overwrite'
  end
end
option_parse.parse!


EXCLUDE_FILES = %w{install README.md .git}

def files_to_link
  current_files = Dir.entries(Dir.pwd)
  current_files.shift 3
  EXCLUDE_FILES.each {|no_install| current_files.delete(no_install)}
  current_files
end

def create_symlinks(files_to_link)
  files_to_link.each do |dotfile|
    home_file_path = "#{Dir.home}/.#{dotfile}"
    FileUtils.mv(home_file_path, home_file_path + '_old') if $options[:force]
    File.symlink("#{Dir.pwd}/#{dotfile}", "#{Dir.home}/.#{dotfile}")
  end
end

puts "============Creating links for======="
if ARGV.empty?
  create_symlinks files_to_link
else
  create_symlinks ARGV
end
puts "============Done====================="

